fix docker_api_version of repo
devopshq/artifactory pull request #361
Opened 2022-08-12 10:18 UTC by donhui

fix #333

2022-08-12 12:51 UTC, beliaev-maksim requested changes
if I am not mistaken, then this feature is not available in all versions of artifactory. Then, if user uses some old version it may get broken. Adding `None` should help

2022-08-12 12:51 UTC, beliaev-maksim commented on dohq_artifactory/admin.py
> +        self.docker_api_version = response.get("dockerApiVersion")
```suggestion
        self.docker_api_version = response.get("dockerApiVersion", None)
```

2022-08-12 12:51 UTC, beliaev-maksim commented on dohq_artifactory/admin.py
> +        self.docker_api_version = response.get("dockerApiVersion")
```suggestion
        self.docker_api_version = response.get("dockerApiVersion", None)
```

2022-08-12 14:39 UTC, donhui commented on dohq_artifactory/admin.py
> +        self.docker_api_version = response.get("dockerApiVersion")
```suggestion
        self.docker_api_version = response.get("dockerApiVersion")
```

2022-08-12 14:44 UTC, donhui commented
@beliaev-maksim
Thanks for your suggestion, I hava updated the code.

2022-08-12 15:47 UTC, beliaev-maksim approved these changes

2022-08-15 06:57 UTC, allburov approved these changes

2022-08-15 06:59 UTC, merged