check if missing API caused by lack of Pro license
devopshq/artifactory pull request #383
Opened 2022-10-03 08:20 UTC by fuzzmz

When using Artifactory OSS some API calls are blocked behind a 400 response with a specific message.

Add better logging for this case.

Fixes #356

2022-10-03 08:35 UTC, beliaev-maksim requested changes
Please add https to the url, some logging parsers may automatically convert it hyperlink

2022-10-03 08:40 UTC, beliaev-maksim approved these changes

2022-10-03 08:41 UTC, fuzzmz commented
@beliaev-maksim, done. By the way, any chance to have the projects under `devopshq` as part of [Hacktoberfest 2022](https://hacktoberfest.com/participation/)? Might encourage even more contributors.

2022-10-03 08:48 UTC, beliaev-maksim commented
@fuzzmz
As far as I remember we need to register our project on hacktoberfest site
Add project tag
Add tags to issues and prs

That is a good idea!

@allburov
Can you register us please, might require admin access?
I can add PR tags

2022-10-05 05:38 UTC, allburov approved these changes
Great, thank you!

2022-10-05 05:39 UTC, merged