added defaultDeploymentRepo on RepositoryVirtual
devopshq/artifactory pull request #461
Opened 2024-12-12 13:44 UTC by PatriceG

I added support to set the default deployment repo name, that we need.
It's fixing issue #460

2024-12-12 14:40 UTC, beliaev-maksim requested changes
also need tests for this

2024-12-12 14:40 UTC, beliaev-maksim commented on dohq_artifactory/admin.py
> +        default_deployment_repo_name=None
it is not an attribute of the class

and should we have it as such?

2024-12-12 14:49 UTC, PatriceG commented
sorry indeed it should be 
self.default_deployment_repo_name=None

I'm not sure I understand how to setup a test environment for your lib.

2024-12-13 08:04 UTC, beliaev-maksim commented
please provide a unittest with mocks, we use `responses`

2024-12-13 13:20 UTC, PatriceG commented
I'm not familiar with mocking in Python.
I'm not sure I understand how to setup a test environment for your lib.
I just wanted to contribute this fix in the lib (I do have a workaround by sublcassing the RepositoryVirutal class but it's not ieal).

2024-12-13 15:16 UTC, beliaev-maksim commented
these are the classic unit tests:
https://github.com/devopshq/artifactory/blob/master/docs/CONTRIBUTE.md#unit

then you can see the `unit` folder and add new tests similar to other

2024-12-16 15:52 UTC, PatriceG commented
There is not a single existing unit test for RepositoryLocal and Virtual.
I'm sorry I have no time to try to understand how to setup a test env.
Feel free to reject my PR if you like. I can do with my local modifications. I just wanted to simply contribute.

2024-12-18 04:13 UTC, merged